name: Bug Report
description: File a bug report
title: "[Bug]: "
body:
 - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
